### ISSUE TITLE
Waterline compatibility

### ISSUE THREAD

**Issue by javiercornejo** [lucianmachado/sails-oracle-database#5]
Hi there.
First I want to than you for this repo! 
Second, I traying to use this adapter but it seems not to be compatible (at least) with the lastest version of Waterline. First hunch came up when waterline alert me that `registerConnection` is not supported anymore and it have to change by `registerDatastore`. Now I am trying to execute a query `model.find().exec(function(err, data){})` and I am getting next error `cb is not a function`.
I'll appreciate your help.
Regards.

**Comment by lucianmachado** [comment]
Hello @javiercornejo,

You're right, this adapter is compatible with 0.10.0 version of waterline.

I've plans to update the version of waterline in the next months.

If you want to contribute, all help will be appreciate!

Regards.

**Comment by javiercornejo** [comment]
Ok thank you @lucianmachado It seem to be working with 0.11.x too.  I'll try to contribute to this fork, I don't know much about integrating adapters in waterline but I'll try.
(Sorry my delayed response, I missed the notification).

Regards!

**Comment by cope** [comment]
It looks like it is not working with waterline 0.13.6 / sails 1.1.0:

> The adapter used by the `xyz` datastore is not compatible with
> the current version of Sails/Waterline.
> 
> The adapter should expose a valid `adapterApiVersion`.

**Comment by cope** [comment]
I created #6
